### PR TITLE
add creator-kit-1.config for led-controller app

### PR DESCRIPTION
**Pull request by mayank-sirotiya-imgtec**
Signed-off-by: Mayank Sirotiya <Mayank.Sirotiya@imgtec.com>

### CODE REVIEW

**Comment by nikhil-zinjurde-imgtec** [comment]
test with jenkins

**Comment by abhijit-mahajani-imgtec** [comment]
Approved

**Comment by nikhil-zinjurde-imgtec** [comment]
build ci

**Comment by nikhil-zinjurde-imgtec** [comment]
Change the build/Makefile to update with creator-kit-1.config

**Comment by nikhil-zinjurde-imgtec** [comment]
QA verified

**Pull request merged**
