### PR TITLE
Fix jobs passed to build OpenWrt

### PR DESCRIPTION
**Pull request by mayank-sirotiya-imgtec**
Signed-off-by: Mayank Sirotiya <Mayank.Sirotiya@imgtec.com>

### CODE REVIEW

**Comment by nikhil-zinjurde-imgtec** [comment]
Approved

**Comment by nikhil-zinjurde-imgtec** [comment]
Actually, we should update the README.md to show use of J parameter

**Comment by nikhil-zinjurde-imgtec** [comment]
Approved

**Comment by abhijit-mahajani-imgtec** [comment]
Approved

**Comment by nikhil-zinjurde-imgtec** [comment]
Verified failed, Makefile:18: *** missing separator

**Comment by nikhil-zinjurde-imgtec** [comment]
Verified

**Pull request merged**
